server:
  port: 8083

spring:
  application:
    name: attendance-service
  datasource:
    url: jdbc:postgresql://localhost:5432/eop-v
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
      show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
