server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/eop
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: nLyOtmxLgpwm2mwAGofAZLwWcAqxVX7/yBNLshXfgHk=
  expiration: 3600000
